SOURCE_MD   := "deep_learning_primer.md"
PROJECT_DIR := "deep_learning_primer"
TITLE       := "Deep Learning and Generative AI: A Technical Primer"
AUTHOR      := "June 2026"
HTML_EXTRA  := "--mathjax"
PDF_EXTRA   := ""

import '../_shared/common.just'
