SOURCE_MD   := "comparative-religion-primer.md"
PROJECT_DIR := "comparative_religion_primer"
TITLE       := "Comparative Religion: Text, Doctrine, Structure, and Liturgy"
AUTHOR      := "August 2026"
HTML_EXTRA  := "--number-sections"
PDF_EXTRA   := "--number-sections"

import '../_shared/common.just'
