SOURCE_MD   := "military_structure_primer.md"
PROJECT_DIR := "military_structure_primer"
TITLE       := "Military Organisation, Ranks, and Doctrine: A Structural Primer"
AUTHOR      := "June 2026"
HTML_EXTRA  := "--mathjax --lua-filter=filters/mermaid-to-image.lua --number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "-V mainfont='DejaVu Serif' -V sansfont='DejaVu Sans' -V monofont='DejaVu Sans Mono' --lua-filter=filters/mermaid-to-image.lua --number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
