SOURCE_MD   := "numerical_analysis_primer.md"
PROJECT_DIR := "numerical_analysis_primer"
TITLE       := "Numerical Analysis Primer: A Practical Guide for Practitioners"
AUTHOR      := "May 2026"
HTML_EXTRA  := "--mathjax"
PDF_EXTRA   := ""

import '../_shared/common.just'

# HTML math variants (different output filenames from shared html recipe)
html-mathml:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{REPO_ROOT}}:/repo{{MOUNT_SUFFIX}}" \
    -w "/repo/{{PROJECT_DIR}}" \
    {{IMAGE}} \
    {{SOURCE_MD}} -o numerical_analysis_primer.mathml.html \
    {{HTML_FLAGS_BASE}} --mathml \
    --template="{{TEMPLATE}}" \
    --metadata title="{{TITLE}}" \
    --metadata author="{{AUTHOR}}"

html-mathjax:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{REPO_ROOT}}:/repo{{MOUNT_SUFFIX}}" \
    -w "/repo/{{PROJECT_DIR}}" \
    {{IMAGE}} \
    {{SOURCE_MD}} -o numerical_analysis_primer.mathjax.html \
    {{HTML_FLAGS_BASE}} --mathjax \
    --template="{{TEMPLATE}}" \
    --metadata title="{{TITLE}}" \
    --metadata author="{{AUTHOR}}"

html-variants: html-mathml html-mathjax
