SOURCE_MD   := "hermes_server_primer.md"
PROJECT_DIR := "hermes_server_primer"
TITLE       := "Hermes Agent Server: A Long-Form, Operations-First Primer"
AUTHOR      := "22 August 2026"
HTML_EXTRA  := "--number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
