SOURCE_MD   := "information_theory_series_combined.md"
PROJECT_DIR := "article_info_theory"
TITLE       := "Information About Information: An Information Theory Series"
AUTHOR      := "Marianne Freiberger"
HTML_EXTRA  := "--mathml --metadata mathrenderer=mathml --number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'

html-mathml:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{REPO_ROOT}}:/repo{{MOUNT_SUFFIX}}" \
    -w "/repo/{{PROJECT_DIR}}" \
    {{IMAGE}} \
    {{SOURCE_MD}} -o information_theory_series_combined.mathml.html \
    {{HTML_FLAGS_BASE}} --mathml --metadata mathrenderer=mathml \
    --number-sections --shift-heading-level-by=-1 \
    --template="{{TEMPLATE}}" \
    --metadata title="{{TITLE}}" \
    --metadata author="{{AUTHOR}}"

html-mathjax:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{REPO_ROOT}}:/repo{{MOUNT_SUFFIX}}" \
    -w "/repo/{{PROJECT_DIR}}" \
    {{IMAGE}} \
    {{SOURCE_MD}} -o information_theory_series_combined.mathjax.html \
    {{HTML_FLAGS_BASE}} --mathjax --metadata mathrenderer=mathjax \
    --number-sections --shift-heading-level-by=-1 \
    --template="{{TEMPLATE}}" \
    --metadata title="{{TITLE}}" \
    --metadata author="{{AUTHOR}}"

html-variants: html-mathml html-mathjax

all-docs: html-variants all
