SOURCE_MD   := "primer_containerization.md"
PROJECT_DIR := "primer_containerization"
TITLE       := "Containerization: Docker, Podman, and How Kubernetes Fits In"
AUTHOR      := "September 2026"
HTML_EXTRA  := "--lua-filter=filters/mermaid-to-image.lua --number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--lua-filter=filters/mermaid-to-image.lua --number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
