SOURCE_MD   := "european-electoral-systems-primer.md"
PROJECT_DIR := "political_systems"
TITLE       := "A Practical Primer On European Electoral Systems"
AUTHOR      := "May 2026"
HTML_EXTRA  := "--number-sections --mathml --metadata mathrenderer=mathml"
PDF_EXTRA   := "--number-sections"

import '../_shared/common.just'

html-mathml:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{REPO_ROOT}}:/repo{{MOUNT_SUFFIX}}" \
    -w "/repo/{{PROJECT_DIR}}" \
    {{IMAGE}} \
    {{SOURCE_MD}} -o european-electoral-systems-primer.mathml.html \
    {{HTML_FLAGS_BASE}} --number-sections --mathml --metadata mathrenderer=mathml \
    --template="{{TEMPLATE}}" \
    --metadata title="{{TITLE}}" \
    --metadata author="{{AUTHOR}}"

html-mathjax:
  {{OCI}} run --rm {{OCI_FLAGS}} \
    -v "{{REPO_ROOT}}:/repo{{MOUNT_SUFFIX}}" \
    -w "/repo/{{PROJECT_DIR}}" \
    {{IMAGE}} \
    {{SOURCE_MD}} -o european-electoral-systems-primer.mathjax.html \
    {{HTML_FLAGS_BASE}} --number-sections --mathjax --metadata mathrenderer=mathjax \
    --template="{{TEMPLATE}}" \
    --metadata title="{{TITLE}}" \
    --metadata author="{{AUTHOR}}"

html-variants: html-mathml html-mathjax

all-docs: html-variants all
