SOURCE_MD   := "european-electoral-systems-primer.md"
PROJECT_DIR := "political_systems"
TITLE       := "A Practical Primer On European Electoral Systems"
AUTHOR      := "May 2026"
HTML_EXTRA  := "--number-sections --mathjax"
PDF_EXTRA   := "--number-sections"

import '../_shared/common.just'
