SOURCE_MD   := "primer_pi_coding_agent.md"
PROJECT_DIR := "primer_pi_coding_agent"
TITLE       := "Pi Coding Agent: A Practical Primer"
AUTHOR      := "24 September 2026"
HTML_EXTRA  := "--number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
