SOURCE_MD   := "primer-comparative-religion.md"
PROJECT_DIR := "primer_comparative_religion"
TITLE       := "Comparative Religion: Text, Doctrine, Structure, and Liturgy"
AUTHOR      := "August 2026"
HTML_EXTRA  := "--number-sections"
PDF_EXTRA   := "--number-sections"

import '../_shared/common.just'
