SOURCE_MD   := "primer_openclaw.md"
PROJECT_DIR := "primer_openclaw"
TITLE       := "OpenClaw: A Comprehensive, Podman-First Guide (October 7, 2026 Refresh)"
AUTHOR      := "7 October 2026"
HTML_EXTRA  := "--number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
