SOURCE_MD   := "primer_openclaw.md"
PROJECT_DIR := "primer_openclaw"
TITLE       := "OpenClaw: A Comprehensive, Podman-First Guide"
AUTHOR      := "22 August 2026"
HTML_EXTRA  := "--number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
