SOURCE_MD   := "information_theory_series_combined.md"
PROJECT_DIR := "info_theory_article"
TITLE       := "Information about information series"
AUTHOR      := "Marianne Freiberger"
HTML_EXTRA  := "--mathjax --number-sections --shift-heading-level-by=-1"
PDF_EXTRA   := "--number-sections --shift-heading-level-by=-1"

import '../_shared/common.just'
